# Generated by Django 3.0.3 on 2020-03-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_news_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(default='def_bg.jpg', upload_to='news_img'),
        ),
    ]
